#!/bin/bash
###############################################################################
#                                                                             #
#       Script name : compare_file.sh                                         #
#       Discription : This script is to check the file changes agter the      # 
#                     pull from the master repository                         #
#                                                                             #
#       Date created:   06/04/2020                                            #
#                                                                             #
#       Author      :   Kesav Lodhi                                           #
#       Change History :                                                      #
###############################################################################
#setting variables
set -o xtrace

GIT=`which git`
CLONE_DIR=/home/ec2-user/work/release1/
GITHUB_REPOSITORY=https://github.com/kesavlodhi/release1.git
BACKUP_CLONE_DIR=/home/ec2-user/work/backup/release1/
FILE_LIST=/tmp/file_list.txt
LOGFILE=/tmp/logfile.txt 
DIFF_DIR=/tmp/diff.txt
HTMLFILE=/tmp/data.html
LINE=/tmp/lines
#message="auto-commit from $USER@$(hostname -s) on $(date)"

#backup the files from clone directory to Backup directory#
cp -rp $CLONE_DIR/* $BACKUP_CLONE_DIR

#Get the latest code from the remote repository#
cd ${CLONE_DIR}
${GIT} pull origin master

#to check change file list

#diff -q /mnt/d/Code_clone/backup/release1 /mnt/d/Code_clone/release1/ | grep "Only in" > /tmp/t.txt 
diff -q $BACKUP_CLONE_DIR $CLONE_DIR | grep differ > $DIFF_DIR

#file1=/tmp/t1.txt
if [[ -s "$DIFF_DIR" ]] 
  then 
	  echo "some files got changed"
	  cat $DIFF_DIR | awk '{print $2}' | awk -F/ '{ print $7 }' > $FILE_LIST
else
	echo "$DIFF_DIR is empty."
	echo "There are no files changes"
	EMAIL_SUBJECT_NO_CHANGES="Notification - NO CHANGES IN FILES"
	EMAIL_FROM_ADDRESS=Kesavsingh.Lodhi@emeriocorp.com            
	EMAIL_TO_ADDRESS=Kesavsingh.Lodhi@emeriocorp.com
	{
	                echo -e "Dear Team,"
			echo -e "\n No files changed in the remote repository."
			echo -e "\nThis notification has been automatically generated by system monitoring.\nPlease do not reply ! "
       		}| mailx -s "$EMAIL_SUBJECT" -r $EMAIL_FROM_ADDRESS $EMAIL_TO_ADDRESS
	exit 11
fi

for line in `cat $FILE_LIST`
do
	git diff $CLONE_DIR$line $BACKUP_CLONE_DIR$line > $LOGFILE
        a=`awk 'NR==5 {print}' $LOGFILE | cut -d" " -f3`
        echo $line $a > $LINE
        tr ' ' '|' < $LINE >> ${HTMLFILE}
done

EMAIL_SUBJECT="Notification - Below files got changed"
EMAIL_FROM_ADDRESS=Kesavsingh.Lodhi@emeriocorp.com 
EMAIL_TO_ADDRESS=Kesavsingh.Lodhi@emeriocorp.com
#{     
#        echo "Subject: Report" 
#	echo -e "Dear Team,"                                                                            echo -e "\n Please check, Below files got changed after in remote repository."                  echo -e "\nThis notification has been automatically generated by ES systems monitoring.\nPlease do not reply !"
# echo }|# mailx -s "$EMAIL_SUBJECT" -r $EMAIL_FROM_ADDRESS $EMAIL_TO_ADDRESS

(
echo "To: $EMAIL_TO_ADDRESS" 
echo "Subject: $EMAIL_SUBJECT" 
echo "Content-Type: text/html" 
echo
cat $HTMLFILE
echo 
) | /usr/sbin/sendmail -t

# Null the temp files
cat /dev/null > $FILE_LIST
cat /dev/null > $LOGFILE
cat /dev/null > $DIFF_DIR
cat /dev/null > $LINE
